[package]
name = "ping-pong"
version = "0.1.0"
authors = ["GregP <glp@swimr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
